# Generated by Django 4.0.8 on 2026-10-08 01:36

import core.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_corepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title')), ('paragraph', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'ol', 'ul', 'document-link', 'embed', 'code', 'blockquote'], icon='pilcrow')), ('image', core.models.ImageChooserBlock(icon='image'))], use_json_field=True),
        ),
    ]
